name: lighthouse
description: queen CLI , makes it easy to work with queen
version: 0.0.7
homepage: https://github.com/FlutterQueen/lighthouse
repository: https://github.com/FlutterQueen/lighthouse
issue_tracker: https://github.com/FlutterQueen/lighthouse/issues
environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  path: ^1.8.0
  df_builder: ^0.0.4
  args: ^2.3.0
  yaml: ^3.1.0
  recase: ^4.0.0
  nations_assets: 0.0.4
  yaml_edit: ^2.0.1
  cli_dialog: ^0.5.0
  readable: ^0.0.3
  get_it: ^7.2.0
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.19.5
  mockito: ^5.0.17
  build_runner: ^2.1.7

executables:
  lh: lighthouse
  lighthouse: lighthouse

flutter:
  assets:
    - assets/foo.png
    - assets/bar.png
