name: lighthouse
description: lighthouse will watch your project files changes then restart the app

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0
  # watch files system
  watcher: 1.0.0
  # to log in the terminal with colors
  ansicolor:

dev_dependencies:
  # lint
  pedantic: ^1.9.0

executables:
  lh: main
  lighthouse: main
