name: lighthouse
description: queen CLI , support integration with queen packages system
version: 0.0.3-beta
publish_to: "none"
homepage: https://github.com/maxzod/lighthouse
repository: https://github.com/maxzod/lighthouse
issue_tracker: https://github.com/maxzod/lighthouse/issues
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0
  equatable: ^2.0.3
  nations: 0.0.1
  df_builder:
    git:
      url: https://github.com/maxzod/df_builder.git
      ref: a05d738156a027cf2578884edb3ef3b631d81cee
  args: ^2.3.0
  archive: ^3.1.6

dev_dependencies:
  # lint
  lints: ^1.0.1
  flutter_test:
    sdk: flutter

executables:
  lh: lighthouse
  lighthouse: lighthouse
