name: lighthouse
description: lighthouse will watch your project files changes and restart the app automaticity

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: 1.8.0
  # watch files system
  watcher: 1.0.0
  # to log in the terminal with colors
  ansicolor: 2.0.1

dev_dependencies:
  # lint
  pedantic: 1.9.0

executables:
  lh: lighthouse
  lighthouse: lighthouse
